spring.application.name=resto
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Loo tabelid automaatselt JPA-st
spring.jpa.hibernate.ddl-auto=create

# Väljasta H2 konsoli
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL logimine
spring.jpa.show-sql=true
